/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiPersonalizationRouteImport } from './routes/api/personalization'
import { Route as ApiModelRouteImport } from './routes/api/model'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedSetupRouteImport } from './routes/_authed/setup'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'
import { Route as ApiVpsVerifyRouteImport } from './routes/api/vps/verify'
import { Route as ApiVpsStatusStreamRouteImport } from './routes/api/vps/status-stream'
import { Route as ApiVpsStatusRouteImport } from './routes/api/vps/status'
import { Route as ApiVpsProvisionRouteImport } from './routes/api/vps/provision'
import { Route as ApiVpsLogsRouteImport } from './routes/api/vps/logs'
import { Route as ApiVpsDestroyRouteImport } from './routes/api/vps/destroy'
import { Route as ApiVpsChatRouteImport } from './routes/api/vps/chat'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiStripeTopupRouteImport } from './routes/api/stripe/topup'
import { Route as ApiStripePortalRouteImport } from './routes/api/stripe/portal'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiVpsTelegramStreamRouteImport } from './routes/api/vps/telegram/stream'
import { Route as ApiVpsTelegramStatusRouteImport } from './routes/api/vps/telegram/status'
import { Route as ApiVpsTelegramConnectRouteImport } from './routes/api/vps/telegram/connect'
import { Route as ApiVpsTelegramApproveRouteImport } from './routes/api/vps/telegram/approve'
import { Route as ApiAdminVpsMaintainRouteImport } from './routes/api/admin/vps/maintain'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiPersonalizationRoute = ApiPersonalizationRouteImport.update({
  id: '/api/personalization',
  path: '/api/personalization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelRoute = ApiModelRouteImport.update({
  id: '/api/model',
  path: '/api/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSetupRoute = AuthedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiVpsVerifyRoute = ApiVpsVerifyRouteImport.update({
  id: '/api/vps/verify',
  path: '/api/vps/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsStatusStreamRoute = ApiVpsStatusStreamRouteImport.update({
  id: '/api/vps/status-stream',
  path: '/api/vps/status-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsStatusRoute = ApiVpsStatusRouteImport.update({
  id: '/api/vps/status',
  path: '/api/vps/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsProvisionRoute = ApiVpsProvisionRouteImport.update({
  id: '/api/vps/provision',
  path: '/api/vps/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsLogsRoute = ApiVpsLogsRouteImport.update({
  id: '/api/vps/logs',
  path: '/api/vps/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsDestroyRoute = ApiVpsDestroyRouteImport.update({
  id: '/api/vps/destroy',
  path: '/api/vps/destroy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsChatRoute = ApiVpsChatRouteImport.update({
  id: '/api/vps/chat',
  path: '/api/vps/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeTopupRoute = ApiStripeTopupRouteImport.update({
  id: '/api/stripe/topup',
  path: '/api/stripe/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsTelegramStreamRoute = ApiVpsTelegramStreamRouteImport.update({
  id: '/api/vps/telegram/stream',
  path: '/api/vps/telegram/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsTelegramStatusRoute = ApiVpsTelegramStatusRouteImport.update({
  id: '/api/vps/telegram/status',
  path: '/api/vps/telegram/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsTelegramConnectRoute = ApiVpsTelegramConnectRouteImport.update({
  id: '/api/vps/telegram/connect',
  path: '/api/vps/telegram/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpsTelegramApproveRoute = ApiVpsTelegramApproveRouteImport.update({
  id: '/api/vps/telegram/approve',
  path: '/api/vps/telegram/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVpsMaintainRoute = ApiAdminVpsMaintainRouteImport.update({
  id: '/api/admin/vps/maintain',
  path: '/api/admin/vps/maintain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/chat': typeof AuthedChatRoute
  '/setup': typeof AuthedSetupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model': typeof ApiModelRoute
  '/api/personalization': typeof ApiPersonalizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/topup': typeof ApiStripeTopupRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/vps/chat': typeof ApiVpsChatRoute
  '/api/vps/destroy': typeof ApiVpsDestroyRoute
  '/api/vps/logs': typeof ApiVpsLogsRoute
  '/api/vps/provision': typeof ApiVpsProvisionRoute
  '/api/vps/status': typeof ApiVpsStatusRoute
  '/api/vps/status-stream': typeof ApiVpsStatusStreamRoute
  '/api/vps/verify': typeof ApiVpsVerifyRoute
  '/api/admin/vps/maintain': typeof ApiAdminVpsMaintainRoute
  '/api/vps/telegram/approve': typeof ApiVpsTelegramApproveRoute
  '/api/vps/telegram/connect': typeof ApiVpsTelegramConnectRoute
  '/api/vps/telegram/status': typeof ApiVpsTelegramStatusRoute
  '/api/vps/telegram/stream': typeof ApiVpsTelegramStreamRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/chat': typeof AuthedChatRoute
  '/setup': typeof AuthedSetupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model': typeof ApiModelRoute
  '/api/personalization': typeof ApiPersonalizationRoute
  '/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/topup': typeof ApiStripeTopupRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/vps/chat': typeof ApiVpsChatRoute
  '/api/vps/destroy': typeof ApiVpsDestroyRoute
  '/api/vps/logs': typeof ApiVpsLogsRoute
  '/api/vps/provision': typeof ApiVpsProvisionRoute
  '/api/vps/status': typeof ApiVpsStatusRoute
  '/api/vps/status-stream': typeof ApiVpsStatusStreamRoute
  '/api/vps/verify': typeof ApiVpsVerifyRoute
  '/api/admin/vps/maintain': typeof ApiAdminVpsMaintainRoute
  '/api/vps/telegram/approve': typeof ApiVpsTelegramApproveRoute
  '/api/vps/telegram/connect': typeof ApiVpsTelegramConnectRoute
  '/api/vps/telegram/status': typeof ApiVpsTelegramStatusRoute
  '/api/vps/telegram/stream': typeof ApiVpsTelegramStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/_authed/setup': typeof AuthedSetupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/model': typeof ApiModelRoute
  '/api/personalization': typeof ApiPersonalizationRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/topup': typeof ApiStripeTopupRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/vps/chat': typeof ApiVpsChatRoute
  '/api/vps/destroy': typeof ApiVpsDestroyRoute
  '/api/vps/logs': typeof ApiVpsLogsRoute
  '/api/vps/provision': typeof ApiVpsProvisionRoute
  '/api/vps/status': typeof ApiVpsStatusRoute
  '/api/vps/status-stream': typeof ApiVpsStatusStreamRoute
  '/api/vps/verify': typeof ApiVpsVerifyRoute
  '/api/admin/vps/maintain': typeof ApiAdminVpsMaintainRoute
  '/api/vps/telegram/approve': typeof ApiVpsTelegramApproveRoute
  '/api/vps/telegram/connect': typeof ApiVpsTelegramConnectRoute
  '/api/vps/telegram/status': typeof ApiVpsTelegramStatusRoute
  '/api/vps/telegram/stream': typeof ApiVpsTelegramStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/chat'
    | '/setup'
    | '/api/health'
    | '/api/model'
    | '/api/personalization'
    | '/api/auth/$'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/topup'
    | '/api/stripe/webhook'
    | '/api/vps/chat'
    | '/api/vps/destroy'
    | '/api/vps/logs'
    | '/api/vps/provision'
    | '/api/vps/status'
    | '/api/vps/status-stream'
    | '/api/vps/verify'
    | '/api/admin/vps/maintain'
    | '/api/vps/telegram/approve'
    | '/api/vps/telegram/connect'
    | '/api/vps/telegram/status'
    | '/api/vps/telegram/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/chat'
    | '/setup'
    | '/api/health'
    | '/api/model'
    | '/api/personalization'
    | '/'
    | '/api/auth/$'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/topup'
    | '/api/stripe/webhook'
    | '/api/vps/chat'
    | '/api/vps/destroy'
    | '/api/vps/logs'
    | '/api/vps/provision'
    | '/api/vps/status'
    | '/api/vps/status-stream'
    | '/api/vps/verify'
    | '/api/admin/vps/maintain'
    | '/api/vps/telegram/approve'
    | '/api/vps/telegram/connect'
    | '/api/vps/telegram/status'
    | '/api/vps/telegram/stream'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/chat'
    | '/_authed/setup'
    | '/api/health'
    | '/api/model'
    | '/api/personalization'
    | '/_authed/'
    | '/api/auth/$'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/topup'
    | '/api/stripe/webhook'
    | '/api/vps/chat'
    | '/api/vps/destroy'
    | '/api/vps/logs'
    | '/api/vps/provision'
    | '/api/vps/status'
    | '/api/vps/status-stream'
    | '/api/vps/verify'
    | '/api/admin/vps/maintain'
    | '/api/vps/telegram/approve'
    | '/api/vps/telegram/connect'
    | '/api/vps/telegram/status'
    | '/api/vps/telegram/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiModelRoute: typeof ApiModelRoute
  ApiPersonalizationRoute: typeof ApiPersonalizationRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeTopupRoute: typeof ApiStripeTopupRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiVpsChatRoute: typeof ApiVpsChatRoute
  ApiVpsDestroyRoute: typeof ApiVpsDestroyRoute
  ApiVpsLogsRoute: typeof ApiVpsLogsRoute
  ApiVpsProvisionRoute: typeof ApiVpsProvisionRoute
  ApiVpsStatusRoute: typeof ApiVpsStatusRoute
  ApiVpsStatusStreamRoute: typeof ApiVpsStatusStreamRoute
  ApiVpsVerifyRoute: typeof ApiVpsVerifyRoute
  ApiAdminVpsMaintainRoute: typeof ApiAdminVpsMaintainRoute
  ApiVpsTelegramApproveRoute: typeof ApiVpsTelegramApproveRoute
  ApiVpsTelegramConnectRoute: typeof ApiVpsTelegramConnectRoute
  ApiVpsTelegramStatusRoute: typeof ApiVpsTelegramStatusRoute
  ApiVpsTelegramStreamRoute: typeof ApiVpsTelegramStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/personalization': {
      id: '/api/personalization'
      path: '/api/personalization'
      fullPath: '/api/personalization'
      preLoaderRoute: typeof ApiPersonalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model': {
      id: '/api/model'
      path: '/api/model'
      fullPath: '/api/model'
      preLoaderRoute: typeof ApiModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/vps/verify': {
      id: '/api/vps/verify'
      path: '/api/vps/verify'
      fullPath: '/api/vps/verify'
      preLoaderRoute: typeof ApiVpsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/status-stream': {
      id: '/api/vps/status-stream'
      path: '/api/vps/status-stream'
      fullPath: '/api/vps/status-stream'
      preLoaderRoute: typeof ApiVpsStatusStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/status': {
      id: '/api/vps/status'
      path: '/api/vps/status'
      fullPath: '/api/vps/status'
      preLoaderRoute: typeof ApiVpsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/provision': {
      id: '/api/vps/provision'
      path: '/api/vps/provision'
      fullPath: '/api/vps/provision'
      preLoaderRoute: typeof ApiVpsProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/logs': {
      id: '/api/vps/logs'
      path: '/api/vps/logs'
      fullPath: '/api/vps/logs'
      preLoaderRoute: typeof ApiVpsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/destroy': {
      id: '/api/vps/destroy'
      path: '/api/vps/destroy'
      fullPath: '/api/vps/destroy'
      preLoaderRoute: typeof ApiVpsDestroyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/chat': {
      id: '/api/vps/chat'
      path: '/api/vps/chat'
      fullPath: '/api/vps/chat'
      preLoaderRoute: typeof ApiVpsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/topup': {
      id: '/api/stripe/topup'
      path: '/api/stripe/topup'
      fullPath: '/api/stripe/topup'
      preLoaderRoute: typeof ApiStripeTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/telegram/stream': {
      id: '/api/vps/telegram/stream'
      path: '/api/vps/telegram/stream'
      fullPath: '/api/vps/telegram/stream'
      preLoaderRoute: typeof ApiVpsTelegramStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/telegram/status': {
      id: '/api/vps/telegram/status'
      path: '/api/vps/telegram/status'
      fullPath: '/api/vps/telegram/status'
      preLoaderRoute: typeof ApiVpsTelegramStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/telegram/connect': {
      id: '/api/vps/telegram/connect'
      path: '/api/vps/telegram/connect'
      fullPath: '/api/vps/telegram/connect'
      preLoaderRoute: typeof ApiVpsTelegramConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vps/telegram/approve': {
      id: '/api/vps/telegram/approve'
      path: '/api/vps/telegram/approve'
      fullPath: '/api/vps/telegram/approve'
      preLoaderRoute: typeof ApiVpsTelegramApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/vps/maintain': {
      id: '/api/admin/vps/maintain'
      path: '/api/admin/vps/maintain'
      fullPath: '/api/admin/vps/maintain'
      preLoaderRoute: typeof ApiAdminVpsMaintainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedChatRoute: typeof AuthedChatRoute
  AuthedSetupRoute: typeof AuthedSetupRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRoute: AuthedChatRoute,
  AuthedSetupRoute: AuthedSetupRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiModelRoute: ApiModelRoute,
  ApiPersonalizationRoute: ApiPersonalizationRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeTopupRoute: ApiStripeTopupRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiVpsChatRoute: ApiVpsChatRoute,
  ApiVpsDestroyRoute: ApiVpsDestroyRoute,
  ApiVpsLogsRoute: ApiVpsLogsRoute,
  ApiVpsProvisionRoute: ApiVpsProvisionRoute,
  ApiVpsStatusRoute: ApiVpsStatusRoute,
  ApiVpsStatusStreamRoute: ApiVpsStatusStreamRoute,
  ApiVpsVerifyRoute: ApiVpsVerifyRoute,
  ApiAdminVpsMaintainRoute: ApiAdminVpsMaintainRoute,
  ApiVpsTelegramApproveRoute: ApiVpsTelegramApproveRoute,
  ApiVpsTelegramConnectRoute: ApiVpsTelegramConnectRoute,
  ApiVpsTelegramStatusRoute: ApiVpsTelegramStatusRoute,
  ApiVpsTelegramStreamRoute: ApiVpsTelegramStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
